apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml . | indent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - nifi
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nifi
          image: parasubvert/nifi:1.6.0
          command: ["/bin/sh","-c"]
          args: ["cd /opt/nifi && ./start_nifi.sh"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 2882
          volumeMounts:
            - name: flowfilerepository
              mountPath: /opt/nifi/flowfile_repository
            - name: databaserepository
              mountPath: /opt/nifi/database_repository
            - name: contentrepository
              mountPath: /opt/nifi/content_repository
            - name: provenancerepository
              mountPath: /opt/nifi/provenance_repository
          env:
            - name: SERVICE
              value: "nifi"
            - name: ZK_NODES_LIST
              value: {{ .Values.zkNodeList }}
            - name: ZK_MONITOR_PORT
              value: "2888"
            - name: IS_CLUSTER_NODE
              value: "yes"
            - name: BANNER_TEXT
              value: "Nifi Cluster"

  volumeClaimTemplates:
  - metadata:
      name: flowfilerepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.repoFlow.size | quote }}
    {{- if .Values.repoFlow.storageClass }}
      {{- if (eq "-" .Values.repoFlow.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.repoFlow.storageClass }}"
      {{- end }}
    {{- end }}
  - metadata:
      name: databaserepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.repoDb.size | quote }}
    {{- if .Values.repoDb.storageClass }}
      {{- if (eq "-" .Values.repoDb.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.repoDb.storageClass }}"
      {{- end }}
    {{- end }}
  - metadata:
      name: contentrepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.repoContent.size | quote }}
    {{- if .Values.repoContent.storageClass }}
      {{- if (eq "-" .Values.repoContent.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.repoContent.storageClass }}"
      {{- end }}
    {{- end }}
  - metadata:
      name: provenancerepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.repoProv.size | quote }}
    {{- if .Values.repoProv.storageClass }}
      {{- if (eq "-" .Values.repoProv.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.repoProv.storageClass }}"
      {{- end }}
    {{- end }}
